name: Push Check

on:
  push:
    branches: [main]
  pull_request: 
    branches: [main]
  schedule:
    - cron: '0 0 * * *'

jobs:
  nodejs-check:
    runs-on: ubuntu-latest
    name: Packages and build check
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 14
      - run: npm ci
      - run: npm run build
      - uses: actions/upload-artifact@v2
        with:
          name: Minified File
          path: dist/peb.min.js


  check-quality:
    runs-on: ubuntu-latest
    name: Codacy Analysis
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Run codacy-analysis-cli
        uses: codacy/codacy-analysis-cli-action@1.1.0
        with:
          project-token: ${{ secrets.CODACY_PROJECT_TOKEN }}
          tool: ESLint

  bundlewatch:
    runs-on: ubuntu-latest
    name: Bundlewatch Check
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 14
      - run: npm install bundlewatch --no-save
      - run: npx bundlewatch --max-size 100KB ./src/*.js
        env:
          BUNDLEWATCH_GITHUB_TOKEN: ${{ secrets.BUNDLEWATCH_GITHUB_TOKEN }}
